= ERC-4337: Account Abstraction Using Alt Mempool

url: https://eips.ethereum.org/EIPS/eip-4337

== Abstract

ERC-4337 は、イーサリアムのアカウント抽象化を実現するための提案で、コンセンサス層（イーサリアムの基盤となる部分）にプロトコルの変更を加えることなく、より高いレイヤーのインフラストラクチャに依存している。

== 目標

ユーザーが現在の外部所有アカウント（EOA）を使用している場合でも、スマートコントラクトアカウント（SCA）をメインのアカウントとして使用できるようにすることを目指している。

=== 利点

* ウォレットにカスタムの認証ロジックを追加できる。
* 開発者がユーザーのガス代を支払う「スポンサー付きトランザクション」を実装できる。

== 仕組み

UserOperation::
ユーザーが実行したい操作を記述する「疑似トランザクション」オブジェクト。通常のイーサリアムトランザクションとは異なり、署名方法やガス台の支払い方法をSCAが柔軟に指定できる。

Memopool::
通常のイーサリアムトランザクションとは異なる、UserOperationを格納するための特別なメモリプール。これにより、SCAは独自のルールでトランザクションを処理できる。

Bundler::
MemopoolからUserOperationを収集し、それらをまとめて単一のイーサリアムトランザクションを作成する特殊なアクター。

Entrypoint::
Bundlerが作成した単一のトランザクションが呼び出す特別なコントラクト。EntryPointコントラクトによって、バンドルされたUserOperationを検証し、実行する中心的な役割を担う。

Paymaster::
送信者以外のコントラクトがUserOperationのガス代を支払うことを可能にするためのヘルパーコントラクト。これにより、ユーザーはERC-20トークンでガス代を支払ったり、開発者がユーザーのガス代を肩代わりしたりすることが可能になる。

== 流れ

. ユーザーは実行したい操作を定義したUserOperationオブジェクトを作成する。
. UserOperationは、署名され、Memopoolに送信される。
. BundlerはMemopoolからUserOperationを収集する。
. Bundlerは、UserOperationをブロックに含める前に、そのUserOperationが有効であり、必要なガス代が支払われていることを確認する（シミュレーション：オフチェーンでの検証）。
. 有効なUserOperationが集まると、Bundlerはそれらをまとめて単一のトランザクションを作成し、EntryPointコントラクトへオンチェーンに提出。
. EntryPointコントラクトは、受け取ったUserOperationの検証と実行を分離して行う。これによって、DoS攻撃からシステムを保護する。

=== ガス代の支払いとDoS対策

* UserOperationの検証と実行は明確に分離されている
    * EntryPointはまずUserOperationが費用を支払うことを保証するメソッドを呼び出す
    * このメソッドが成功した場合のみ、実際にUserOperationを実行する
* 悪意のあるUserOperationがシステムを妨害するのを防ぐため、BundlerはオンチェーンでUserOperationのシミュレーションを行い、検証ルールに準拠していることを確認
* PaymasterやFactoryなどのグローバルなエンティティが大量の無効なUserOperationを引き起こすのを防ぐために、レピュテーションシステムが導入されており、ステークを預けることで信頼性を高める


